--Member--
CREATE TABLE tblFaculty(
faculty_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
faculty_name VARCHAR(75),
CONSTRAINT pk_tblFaculty PRIMARY KEY (faculty_id)
);

INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Arts');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Education');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Graduate Studies');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Indigenous Medicine');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Law');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Management and Finance');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Medicine');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Science');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Technology');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Nursing');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Computing');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Applied Sciences');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Urban and Aquatic Bioresources');
INSERT INTO tblFaculty (faculty_name) VALUES ('Faculty of Engineering');

CREATE TABLE tblMember(
    member_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_tracking_num VARCHAR2(10) NOT NULL,
    member_name VARCHAR2(100) NOT NULL,
    faculty_id NUMBER REFERENCES tblFaculty(faculty_id),
    member_email VARCHAR2(75) NOT NULL,
    member_phone VARCHAR2(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE tblMember
ADD CONSTRAINT unique_member_tracking_num UNIQUE (member_tracking_num);

select * from tblmember;

ALTER TABLE tblMember MODIFY
  PARTITION BY RANGE (member_id)
  (
    PARTITION p1 VALUES LESS THAN (500),
    PARTITION p2 VALUES LESS THAN (1000),
    PARTITION p3 VALUES LESS THAN (MAXVALUE)
  );
CREATE INDEX idx_member_name ON tblMember (member_name)
LOCAL (PARTITION p1, PARTITION p2, PARTITION p3);












--Book--
CREATE TABLE tblBookCategory (
   category_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   category_name VARCHAR2(50) NOT NULL
);

INSERT INTO tblBookCategory (category_name) VALUES ('Fictions');
INSERT INTO tblBookCategory (category_name) VALUES ('Mathematics');--applied science
INSERT INTO tblBookCategory (category_name) VALUES ('Mechanical Engineering');--engineering
INSERT INTO tblBookCategory (category_name) VALUES ('Environmental Science');--urban
INSERT INTO tblBookCategory (category_name) VALUES ('Architecture');--urban
INSERT INTO tblBookCategory (category_name) VALUES ('Biography');
INSERT INTO tblBookCategory (category_name) VALUES ('Languages');--art
INSERT INTO tblBookCategory (category_name) VALUES ('Educational');--art
INSERT INTO tblBookCategory (category_name) VALUES ('Management');--mgt
INSERT INTO tblBookCategory (category_name) VALUES ('History');--art
INSERT INTO tblBookCategory (category_name) VALUES ('Motivational');
INSERT INTO tblBookCategory (category_name) VALUES ('Law');
INSERT INTO tblBookCategory (category_name) VALUES ('Computer Science');
INSERT INTO tblBookCategory (category_name) VALUES ('Medical Science');
INSERT INTO tblBookCategory (category_name) VALUES ('Accounting');--mgt
INSERT INTO tblBookCategory (category_name) VALUES ('Statistics');--applied science
INSERT INTO tblBookCategory (category_name) VALUES ('Religion');--art
INSERT INTO tblBookCategory (category_name) VALUES ('Civil Engineering');--engineering
INSERT INTO tblBookCategory (category_name) VALUES ('Physics');--applied science
INSERT INTO tblBookCategory (category_name) VALUES ('Polymer Science');--applied science
INSERT INTO tblBookCategory (category_name) VALUES ('Plant Biotechnology');--Technology

UPDATE tblBookLoans
SET return_date='18-APR-23'
WHERE loan_id=67;

select * from tblBookLoans;
select  loan_id,return_date_expected, return_date from tblBookLoans;
select * from tblBook;

CREATE TABLE tblBook (
   book_id NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   book_tracking_number VARCHAR(10) NOT NULL UNIQUE,
   book_title VARCHAR2(100) NOT NULL,
   book_author VARCHAR2(100) NOT NULL,
   book_publisher VARCHAR2(100) NOT NULL,
   book_isbn VARCHAR2(20) NOT NULL,
   category_id NUMBER(10) NOT NULL,
   created_at DATE DEFAULT SYSDATE NOT NULL,
   CONSTRAINT fk_categories FOREIGN KEY (category_id) REFERENCES tblbookcategory(category_id)
);

--Lend and Return--
CREATE TABLE tblBookLoans (
   loan_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   loan_tracking_num VARCHAR(10) NOT NULL UNIQUE,
   member_tracking_num VARCHAR2(10) NOT NULL,
   book_tracking_number VARCHAR2(10) NOT NULL,
   loan_date DATE DEFAULT SYSDATE NOT NULL,
   return_date_expected DATE,
   return_date DATE,
   CONSTRAINT fk_members FOREIGN KEY (member_tracking_num) REFERENCES tblMember(member_tracking_num),
   CONSTRAINT fk_books FOREIGN KEY (book_tracking_number) REFERENCES tblBook(book_tracking_number)
);

select * from fine_payments;

/*CREATE TABLE Fine_Payments (
  payment_id GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  payment_tracking_num VARCHAR2(10) UNIQUE,
  loan_tracking_num VARCHAR2(10),
  payment_date DATE,
  payment_amount NUMBER(10,2),
  CONSTRAINT Fine_Payments_loans_fk FOREIGN KEY (loan_tracking_num)
    REFERENCES tblBookLoans (book_tracking_number)
);*/

DELETE FROM fine_payments;

--Drop Statements--
drop table tblBookLoans;

delete from fine_payments
where payment_id = 8;